=== Opposed Checks

In some cases, instead of a simple success / failure binary, a check is attempted against another character. Examples of this may include attempting to lie (Deception vs Insight), attempting to hide (Stealth vs Perception), or attempting certain combat maneuvers (varies). To roll an opposed check, follow the steps below:

. Determine the appropriate skills for both characters. They do not have to be the same skill; as noted above, they often are not. Some actions list specific skills to be used in opposed checks, but others are up to GM discretion.
. Both characters roll against their own thresholds, taking into account all the normal bonuses and penalties of the situation.
. Subtract each character's roll from their threshold to get a Result Factor. The RF will be positive if the character succeeded or negative if they failed.
. Compare the RFs. The character with a higher RF wins the contest, though if they failed their check overall, there may be an additional complication.
.. If both RFs are identical, the character with the higher adjusted threshold value wins.
.. If both RFs and threshold values are identical, the more active character wins.
... For instance, the attacker would win in combat, the searcher would win in stealth, the liar would win in deception, and so on.
.. If the more active character cannot be determined, the GM decides.

==== Active/Passive

. In some circumstances, it may be the case that only one character involved in an opposed check is aware they are participating. Perhaps a character is sneaking (Stealth) past the outskirts of a party, attempting to pickpocket an unaware target (Thievery), or attempting to blend in at the same party (Disguise or Social).
. If this is the case, where there is a defined target to make it an opposed check but the target is not actively participating, you may have the passive character "take a 50" on their check, making their RF equal to their threshold minus 50.
. From there, use the same steps as above to compare the RFs and determine the winner.
.. When using this rule, the passive character always counts as "less active" for tiebreak purposes above.
