=== Skill Challenges

Rolling a skill check is very similar to the basic check outlined in <<#_the_noble_d100>> above.

. The starting threshold is the character's relevant skill. Any permanent bonuses are already factored into this skill.
. Add or subtract from the threshold based on the challenge's difficulty. Each skill's description section (see <<#_skills>>) contains example challenges at various levels of difficulty. However, the GM can reference the table below for general advice applicable to all skills:

+
[cols="20,17,63"]
|===
| Difficulty|Modifier|Description

| Trivial
| +75 or more
| Almost anyone could succeed without much difficulty.

| Simple
| +50
| A trained adult would almost never fail, and an untrained adult would have a decent chance of success.

| Ordinary
| +25
| A trained adult would be very likely to succeed, and an untrained adult would still have a chance of success.

| Straightforward
| +10
| A trained adult would be likely to succeed, and an untrained adult would have a low chance of success.

| Normal
| 0
| A trained adult would find the task challenging but possible, and an untrained adult would still have a very slim chance of success.

| Hard
| -10
| A trained adult would be more likely to fail than succeed, and an untrained adult would find the task essentially impossible.

| Expert
| -25
| A trained adult would struggle to succeed. A prepared master would find the task challenging but possible.

| Extreme
| -50
| A trained adult would have a very slim chance of success. A prepared master would still be more likely to fail than succeed.

| Heroic
| -75 or more
| Essentially impossible without magic, powerful equipment, or supernatural skills.
|===

.. Most challenges should have threshold modifiers between -50 and +50, though the GM may apply any desired modifier. Keep in mind that many trivial or impossible tasks should be automatic successes or failures instead of rolls.
... Threshold modifiers may be considered similar to a "Difficulty Class" for the challenge, for those familiar with roll-over systems.
.. Additionally, tasks without time pressure or without a fail state (for instance, where the characters can retry over and over until they succeed) can be ruled an automatic success. Though if the time passed is important, a roll may still determine how long it takes.
.. Keep in mind that, in this system, an average adult human has B, M, S around 20, an exceptional talent may have up to 50 of an attribute, and a trained professional in a skill may have around 50 ranks in it.

. Add bonuses to the threshold for any non-permanent buffs, circumstances, consumables, etc. (if any).
. Subtract any penalties from the threshold for any non-permanent debuffs, circumstances, effects, etc. (if any).
. Roll a d100. If the result is below the threshold, the check succeeds. If the result is above the threshold, the check fails.

==== Variant Rules: Result Factor instead of Threshold Modifiers

. Sometimes, a character may be attempting a general challenge and may have different chances to succeed against multiple possible outcomes. Alternatively, the very existence of certain outcomes may be secret.
.. For instance, searching a room (Perception) for clues that are hidden with various levels of difficulty, or attempting to diagnose multiple injuries or curses (Medicine or Occult).
. In these cases, instead of adding a threshold modifier as described in the table above, simply roll as normal and determine the Result Factor as described in <<#_opposed_checks>>.
. Then, compare the Result Factor to the the _opposite_ of the threshold modifier from the table above. A higher RF than the modifier is a success; a lower RF is a failure.
.. For instance, a character may be attempting to diagnose another character's illnesses, which are (unknown to the first character) typical, unusual, and magical in nature. The <<#_medicine>> table provides modifiers of Ordinary (+25), Normal (0), and Expert (-25) for these.
.. If the RF of the challenge is +14, the character would identify the Ordinary and Normal illnesses (as -25 and 0 are both less than +14), but would fail to identify the Expert illness (as +25 is more than +14).
. This method may be used to entirely replace the threshold modifier system, if desired; simply treat the suggested modifiers as the opposite of the required RF to achieve a certain outcome.
